name: Nx Affected CI
on: [push]
jobs:
  # install packages
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js âš™ï¸
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies ğŸ“¦
        run: yarn install --frozen-lockfile
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ls node_modules
      - run: npx nx affected --target=lint
      - run: yarn nx affected --target=lint
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "CA VA TEST ${{ runner.os }} - ${{ github.repository }}"
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "CA VA BUILDDDD ${{ runner.os }} - ${{ github.repository }}"
