name: Nx Affected CI
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js âš™ï¸
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies ğŸ“¦
        run: yarn install --frozen-lockfile

  test-and-lint:
    strategy:
      matrix:
        target: ['test', 'lint']
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile # from cache I guess
      - name: Launch ${{matrix.target}} script ğŸ¤–
        run: npx nx ${{matrix.target}} cli

  build:
    runs-on: ubuntu-latest
    needs: [test-and-lint]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile # from cache I guess
      - name: Build DotCli ğŸ—ï¸
        run: npx nx package cli
      - uses: actions/upload-artifact@v2
        with:
          name: buildDist
          path: dist

  # deploy-package:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   if: github.ref == 'refs/heads/main' # only for main
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/download-artifact@master
  #       with:
  #         name: buildDist
  #         path: dist
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'
  #         cache: 'yarn'
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: ls
  #       working-directory: './dist/packages/cli'
  #     - name: Deploy to NPM ğŸš€
  #       working-directory: './dist/packages/cli'
  #       run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
