# - uses: actions/checkout@v2
# - run: ls
# - run: npx nx affected --target=lint
# - run: yarn nx affected --target=lint
name: Nx Affected CI
on: [push]
jobs:
  # install packages
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js âš™ï¸
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies ğŸ“¦
        run: yarn install --frozen-lockfile
      - run: ls

  test-and-lint:
    strategy:
      matrix:
        target: ['test', 'lint']
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v2
      # - run: git fetch origin main
      # - run: git fetch --no-tags --prune --depth=1 origin main
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile # from cache I guess
      - run: npx nx run-many --target=${{ matrix.target}} --all

  build:
    needs: [test-and-lint]
    runs-on: ubuntu-latest
    steps:
      - run: echo "CA VA BUILDDDD ${{ runner.os }} - ${{ github.repository }}"
