name: Nx Affected CI
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js âš™ï¸
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies ğŸ“¦
        run: yarn install --frozen-lockfile

  test-and-lint:
    strategy:
      matrix:
        target: ['test', 'lint']
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile # from cache I guess
      - run: npx nx ${{matrix.target}} cli

  build:
    runs-on: ubuntu-latest
    needs: [test-and-lint]
    steps:
      - run: npx nx build cli

  deploy-package:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main' # only for master
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: echo "CA VA DEPLOY"
